services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: example
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["/venv/bin/python3", "-m", "uvicorn", "app:app", "--host=0.0.0.0", "--port=8000"]
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test-password
    ports:
      - "5432:5432"

